// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-bank-io/ent/runtime.go

const (
	Version = "v0.10.2-0.20220606145555-9e4660f10448"           // Version of ent codegen.
	Sum     = "h1:Mm5m5rdLI2S/RW8UzXLRP8IneV7kcWAKYTNYh1U9gMI=" // Sum of ent codegen.
)
